version: '3.7'

services:
  web:
    container_name: books_api
    build:
      context: books_api
      dockerfile: Dockerfile.development
    entrypoint: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.development
    volumes:
      - ./books_api:/app
