# Generated by Django 5.1.6 on 2025-03-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="isbn10",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="isbn13",
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="number_of_pages",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="publish_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="subtitle",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
