# Generated by Django 5.1.6 on 2025-03-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "books",
            "0002_alter_bookmodel_description_alter_bookmodel_isbn10_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
