# Generated by Django 5.1.6 on 2025-03-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_bookmodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="id",
            field=models.UUIDField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
