name: CI - Django

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up application
        run: make up-dev
      - name: Run tests
        run: make test
      - name: Stop application
        run: make clean
